version: "3.8"
services:
  wordle-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: wordle-bot:latest
    env_file:
      - .env          
    volumes:
      - ./assets:/app/assets:ro
    restart: unless-stopped
